// -*- C++ -*- generated by wxGlade 0.6.3

#include <wx/wx.h>
#include <wx/image.h>
// begin wxGlade: ::dependencies
// end wxGlade


#ifndef GROUPEDITORDIALOGBASE_H
#define GROUPEDITORDIALOGBASE_H


// begin wxGlade: ::extracode
enum {
  ID_GROUPEDIT_DLG_BUTTON_Save,
  ID_GROUPEDIT_DLG_BUTTON_Cancel,
  ID_GROUPEDIT_DLG_BUTTON_SelectFile,
  ID_GROUPEDIT_DLG_BUTTON_SelectFolder,
  ID_GROUPEDIT_DLG_BUTTON_ChangeIcon
};
// end wxGlade


class GroupEditorDialogBase: public wxDialog {
public:
    // begin wxGlade: GroupEditorDialogBase::ids
    // end wxGlade

    GroupEditorDialogBase(wxWindow* parent, int id, const wxString& title, const wxPoint& pos=wxDefaultPosition, const wxSize& size=wxDefaultSize, long style=wxDEFAULT_DIALOG_STYLE);

private:
    // begin wxGlade: GroupEditorDialogBase::methods
    void set_properties();
    void do_layout();
    // end wxGlade

protected:
    // begin wxGlade: GroupEditorDialogBase::attributes
    wxStaticText* nameLabel;
    wxTextCtrl* nameTextBox;
    wxStaticText* iconLabel;
    wxStaticBitmap* iconBitmap;
    wxButton* changeIconButton;
    wxButton* saveButton;
    wxButton* cancelButton;
    // end wxGlade
}; // wxGlade: end class


#endif // GROUPEDITORDIALOGBASE_H
