// -*- C++ -*- generated by wxGlade 0.6.3

#include "ConfigDialogBase.h"

// begin wxGlade: ::extracode

// end wxGlade



ConfigDialogBase::ConfigDialogBase(wxWindow* parent, int id, const wxString& title, const wxPoint& pos, const wxSize& size, long style):
    wxDialog(parent, id, title, pos, size, wxDEFAULT_DIALOG_STYLE)
{
    // begin wxGlade: ConfigDialogBase::ConfigDialogBase
    notebook = new wxNotebook(this, wxID_ANY, wxDefaultPosition, wxDefaultSize, 0);
    notebook_1_pane_1 = new wxPanel(notebook, wxID_ANY);
    languageLabel = new wxStaticText(notebook_1_pane_1, wxID_ANY, wxT("Language:"));
    const wxString *languageComboBox_choices = NULL;
    languageComboBox = new wxComboBox(notebook_1_pane_1, wxID_ANY, wxT(""), wxDefaultPosition, wxDefaultSize, 0, languageComboBox_choices, wxCB_DROPDOWN|wxCB_READONLY);
    iconSizeLabel = new wxStaticText(notebook_1_pane_1, wxID_ANY, wxT("Icon size:"));
    const wxString *iconSizeComboBox_choices = NULL;
    iconSizeComboBox = new wxComboBox(notebook_1_pane_1, wxID_ANY, wxT(""), wxDefaultPosition, wxDefaultSize, 0, iconSizeComboBox_choices, wxCB_DROPDOWN|wxCB_READONLY);
    saveButton = new wxButton(this, ID_CDLG_BUTTON_Save, wxT("Save"));
    cancelButton = new wxButton(this, ID_CDLG_BUTTON_Cancel, wxT("Cancel"));

    set_properties();
    do_layout();
    // end wxGlade
}


void ConfigDialogBase::set_properties()
{
    // begin wxGlade: ConfigDialogBase::set_properties
    SetTitle(wxT("dialog_1"));
    SetSize(wxSize(323, 192));
    // end wxGlade
}


void ConfigDialogBase::do_layout()
{
    // begin wxGlade: ConfigDialogBase::do_layout
    wxBoxSizer* sizer_1 = new wxBoxSizer(wxVERTICAL);
    wxBoxSizer* sizer_2 = new wxBoxSizer(wxHORIZONTAL);
    wxBoxSizer* sizer_3 = new wxBoxSizer(wxHORIZONTAL);
    wxFlexGridSizer* generalGridSizer = new wxFlexGridSizer(2, 2, 8, 8);
    generalGridSizer->Add(languageLabel, 0, wxALIGN_CENTER_VERTICAL, 0);
    generalGridSizer->Add(languageComboBox, 0, wxEXPAND, 0);
    generalGridSizer->Add(iconSizeLabel, 0, wxALIGN_CENTER_VERTICAL, 0);
    generalGridSizer->Add(iconSizeComboBox, 0, wxEXPAND, 0);
    generalGridSizer->AddGrowableCol(1);
    sizer_3->Add(generalGridSizer, 1, wxALL|wxEXPAND, 10);
    notebook_1_pane_1->SetSizer(sizer_3);
    notebook->AddPage(notebook_1_pane_1, wxT("General"));
    sizer_1->Add(notebook, 1, wxLEFT|wxRIGHT|wxTOP|wxEXPAND, 4);
    sizer_2->Add(saveButton, 0, wxRIGHT|wxALIGN_BOTTOM, 8);
    sizer_2->Add(cancelButton, 0, wxALIGN_BOTTOM, 0);
    sizer_1->Add(sizer_2, 0, wxALL|wxALIGN_RIGHT, 10);
    SetSizer(sizer_1);
    Layout();
    // end wxGlade
}

