// -*- C++ -*- generated by wxGlade 0.6.3

#include "IconDialogBase.h"

// begin wxGlade: ::extracode

// end wxGlade



IconDialogBase::IconDialogBase(wxWindow* parent, int id, const wxString& title, const wxPoint& pos, const wxSize& size, long style):
    wxDialog(parent, id, title, pos, size, wxDEFAULT_DIALOG_STYLE)
{
    // begin wxGlade: IconDialogBase::IconDialogBase
    label_1 = new wxStaticText(this, wxID_ANY, wxT("Icon file:"));
    text_ctrl_1 = new wxTextCtrl(this, wxID_ANY, wxEmptyString);
    listViewPlaceHolder = new wxStaticText(this, wxID_ANY, wxT("label_1"));
    button_2 = new wxButton(this, wxID_ANY, wxT("button_2"));
    button_3 = new wxButton(this, wxID_ANY, wxT("button_3"));

    set_properties();
    do_layout();
    // end wxGlade
}


void IconDialogBase::set_properties()
{
    // begin wxGlade: IconDialogBase::set_properties
    SetTitle(wxT("Edit group"));
    SetSize(wxSize(336, 349));
    // end wxGlade
}


void IconDialogBase::do_layout()
{
    // begin wxGlade: IconDialogBase::do_layout
    wxBoxSizer* sizer_1 = new wxBoxSizer(wxHORIZONTAL);
    wxFlexGridSizer* grid_sizer_1 = new wxFlexGridSizer(3, 1, 8, 8);
    wxFlexGridSizer* grid_sizer_3 = new wxFlexGridSizer(1, 3, 0, 8);
    wxFlexGridSizer* grid_sizer_2 = new wxFlexGridSizer(1, 2, 0, 8);
    grid_sizer_2->Add(label_1, 0, 0, 0);
    grid_sizer_2->Add(text_ctrl_1, 0, wxEXPAND, 0);
    grid_sizer_2->AddGrowableCol(1);
    grid_sizer_1->Add(grid_sizer_2, 1, wxEXPAND, 0);
    grid_sizer_1->Add(listViewPlaceHolder, 0, 0, 0);
    grid_sizer_3->Add(button_2, 0, 0, 0);
    grid_sizer_3->Add(button_3, 0, 0, 0);
    grid_sizer_3->AddGrowableCol(0);
    grid_sizer_1->Add(grid_sizer_3, 1, wxEXPAND, 0);
    grid_sizer_1->AddGrowableCol(0);
    sizer_1->Add(grid_sizer_1, 1, wxALL|wxEXPAND, 8);
    SetSizer(sizer_1);
    Layout();
    // end wxGlade
}

