// -*- C++ -*- generated by wxGlade 0.6.3

#include <wx/wx.h>
#include <wx/image.h>
// begin wxGlade: ::dependencies
#include <wx/treectrl.h>
// end wxGlade


#ifndef TREEVIEWDIALOGBASE_H
#define TREEVIEWDIALOGBASE_H


// begin wxGlade: ::extracode
enum {
ID_TREEVIEW_DLG_treeControl
};
// end wxGlade


class TreeViewDialogBase: public wxDialog {
public:
    // begin wxGlade: TreeViewDialogBase::ids
    // end wxGlade

    TreeViewDialogBase(wxWindow* parent, int id, const wxString& title, const wxPoint& pos=wxDefaultPosition, const wxSize& size=wxDefaultSize, long style=wxDEFAULT_DIALOG_STYLE);

private:
    // begin wxGlade: TreeViewDialogBase::methods
    void set_properties();
    void do_layout();
    // end wxGlade

protected:
    // begin wxGlade: TreeViewDialogBase::attributes
    wxTreeCtrl* treeControl;
    // end wxGlade
}; // wxGlade: end class


#endif // TREEVIEWDIALOGBASE_H
