// -*- C++ -*- generated by wxGlade 0.6.3

#include "TreeViewDialogBase.h"

// begin wxGlade: ::extracode

// end wxGlade



TreeViewDialogBase::TreeViewDialogBase(wxWindow* parent, int id, const wxString& title, const wxPoint& pos, const wxSize& size, long style):
    wxDialog(parent, id, title, pos, size, wxDEFAULT_DIALOG_STYLE|wxRESIZE_BORDER|wxTHICK_FRAME)
{
    // begin wxGlade: TreeViewDialogBase::TreeViewDialogBase
    treeControl = new wxTreeCtrl(this, ID_TREEVIEW_DLG_treeControl, wxDefaultPosition, wxDefaultSize, wxTR_HAS_BUTTONS|wxTR_LINES_AT_ROOT|wxTR_DEFAULT_STYLE|wxSUNKEN_BORDER);
    closeButton = new wxButton(this, ID_TREEVIEW_DLG_closeButton, wxT("Close"));

    set_properties();
    do_layout();
    // end wxGlade
}


void TreeViewDialogBase::set_properties()
{
    // begin wxGlade: TreeViewDialogBase::set_properties
    SetTitle(wxT("dialog_1"));
    SetSize(wxSize(222, 343));
    // end wxGlade
}


void TreeViewDialogBase::do_layout()
{
    // begin wxGlade: TreeViewDialogBase::do_layout
    wxBoxSizer* sizer_1 = new wxBoxSizer(wxHORIZONTAL);
    wxBoxSizer* sizer_2 = new wxBoxSizer(wxVERTICAL);
    sizer_2->Add(treeControl, 1, wxEXPAND, 0);
    sizer_2->Add(closeButton, 0, wxTOP|wxEXPAND, 8);
    sizer_1->Add(sizer_2, 1, wxALL|wxEXPAND, 8);
    SetSizer(sizer_1);
    Layout();
    // end wxGlade
}

