// -*- C++ -*- generated by wxGlade 0.6.3

#include <wx/wx.h>
#include <wx/image.h>
// begin wxGlade: ::dependencies
#include <wx/notebook.h>
// end wxGlade


#ifndef ABOUTDIALOGBASE_H
#define ABOUTDIALOGBASE_H


// begin wxGlade: ::extracode
enum {
ID_ABOUT_DLG_BUTTON_OK
};
// end wxGlade


class AboutDialogBase: public wxDialog {
public:
    // begin wxGlade: AboutDialogBase::ids
    // end wxGlade

    AboutDialogBase(wxWindow* parent, int id, const wxString& title, const wxPoint& pos=wxDefaultPosition, const wxSize& size=wxDefaultSize, long style=wxDEFAULT_DIALOG_STYLE);

private:
    // begin wxGlade: AboutDialogBase::methods
    void set_properties();
    void do_layout();
    // end wxGlade

protected:
    // begin wxGlade: AboutDialogBase::attributes
    wxStaticBitmap* iconBitmap;
    wxTextCtrl* versionLabel;
    wxStaticText* label_2;
    wxStaticText* authorLabel;
    wxStaticText* label_1;
    wxStaticText* linkLabel;
    wxStaticText* creditLabel;
    wxTextCtrl* creditTextBox;
    wxPanel* notebook_1_pane_1;
    wxTextCtrl* text_ctrl_1;
    wxPanel* notebook_pane_2;
    wxNotebook* notebook;
    wxButton* okButton;
    // end wxGlade
}; // wxGlade: end class


#endif // ABOUTDIALOGBASE_H
