// -*- C++ -*- generated by wxGlade 0.6.3

#include "ConfigDialogBase.h"

// begin wxGlade: ::extracode

// end wxGlade



ConfigDialogBase::ConfigDialogBase(wxWindow* parent, int id, const wxString& title, const wxPoint& pos, const wxSize& size, long style):
    wxDialog(parent, id, title, pos, size, wxDEFAULT_DIALOG_STYLE)
{
    // begin wxGlade: ConfigDialogBase::ConfigDialogBase
    notebook = new wxNotebook(this, wxID_ANY, wxDefaultPosition, wxDefaultSize, 0);
    notebook_pane_2 = new wxPanel(notebook, wxID_ANY);
    notebook_1_pane_1 = new wxPanel(notebook, wxID_ANY);
    languageLabel = new wxStaticText(notebook_1_pane_1, wxID_ANY, wxT("Language:"));
    const wxString *languageComboBox_choices = NULL;
    languageComboBox = new wxComboBox(notebook_1_pane_1, wxID_ANY, wxT(""), wxDefaultPosition, wxDefaultSize, 0, languageComboBox_choices, wxCB_DROPDOWN|wxCB_READONLY);
    label_1 = new wxStaticText(notebook_1_pane_1, wxID_ANY, wxEmptyString);
    autohideCheckBox = new wxCheckBox(notebook_1_pane_1, wxID_ANY, wxT("Hide after launching an application"));
    label_2 = new wxStaticText(notebook_1_pane_1, wxID_ANY, wxEmptyString);
    alwaysOnTopCheckBox = new wxCheckBox(notebook_1_pane_1, wxID_ANY, wxT("Always on top"));
    label_3 = new wxStaticText(notebook_1_pane_1, wxID_ANY, wxEmptyString);
    oneInstanceCheckBox = new wxCheckBox(notebook_1_pane_1, wxID_ANY, wxT("Allow only one instance of %s at a time"));
    label_4 = new wxStaticText(notebook_1_pane_1, wxID_ANY, wxEmptyString);
    checkForUpdateButton = new wxButton(notebook_1_pane_1, ID_CDLG_BUTTON_CheckForUpdate, wxT("Check for update"));
    iconSizeLabel = new wxStaticText(notebook_pane_2, wxID_ANY, wxT("Icon size:"));
    const wxString *iconSizeComboBox_choices = NULL;
    iconSizeComboBox = new wxComboBox(notebook_pane_2, wxID_ANY, wxT(""), wxDefaultPosition, wxDefaultSize, 0, iconSizeComboBox_choices, wxCB_DROPDOWN|wxCB_READONLY);
    orientationLabel = new wxStaticText(notebook_pane_2, wxID_ANY, wxT("Orientation:"));
    const wxString *orientationComboBox_choices = NULL;
    orientationComboBox = new wxComboBox(notebook_pane_2, wxID_ANY, wxT(""), wxDefaultPosition, wxDefaultSize, 0, orientationComboBox_choices, wxCB_DROPDOWN|wxCB_READONLY);
    skinLabel = new wxStaticText(notebook_pane_2, wxID_ANY, wxT("Skin:"));
    const wxString *skinComboBox_choices = NULL;
    skinComboBox = new wxComboBox(notebook_pane_2, wxID_ANY, wxT(""), wxDefaultPosition, wxDefaultSize, 0, skinComboBox_choices, wxCB_DROPDOWN|wxCB_READONLY);
    saveButton = new wxButton(this, ID_CDLG_BUTTON_Save, wxT("Save"));
    cancelButton = new wxButton(this, ID_CDLG_BUTTON_Cancel, wxT("Cancel"));

    set_properties();
    do_layout();
    // end wxGlade
}


void ConfigDialogBase::set_properties()
{
    // begin wxGlade: ConfigDialogBase::set_properties
    SetTitle(wxT("dialog_1"));
    SetSize(wxSize(374, 250));
    // end wxGlade
}


void ConfigDialogBase::do_layout()
{
    // begin wxGlade: ConfigDialogBase::do_layout
    wxBoxSizer* sizer_1 = new wxBoxSizer(wxVERTICAL);
    wxBoxSizer* sizer_2 = new wxBoxSizer(wxHORIZONTAL);
    wxBoxSizer* sizer_4 = new wxBoxSizer(wxHORIZONTAL);
    wxFlexGridSizer* grid_sizer_1 = new wxFlexGridSizer(3, 2, 8, 8);
    wxBoxSizer* sizer_3 = new wxBoxSizer(wxHORIZONTAL);
    wxFlexGridSizer* generalGridSizer = new wxFlexGridSizer(5, 2, 8, 8);
    generalGridSizer->Add(languageLabel, 0, wxALIGN_CENTER_VERTICAL, 0);
    generalGridSizer->Add(languageComboBox, 0, wxEXPAND, 0);
    generalGridSizer->Add(label_1, 0, 0, 0);
    generalGridSizer->Add(autohideCheckBox, 0, 0, 0);
    generalGridSizer->Add(label_2, 0, 0, 0);
    generalGridSizer->Add(alwaysOnTopCheckBox, 0, 0, 0);
    generalGridSizer->Add(label_3, 0, 0, 0);
    generalGridSizer->Add(oneInstanceCheckBox, 0, 0, 0);
    generalGridSizer->Add(label_4, 0, 0, 0);
    generalGridSizer->Add(checkForUpdateButton, 0, wxEXPAND, 0);
    generalGridSizer->AddGrowableCol(1);
    sizer_3->Add(generalGridSizer, 1, wxALL|wxEXPAND, 10);
    notebook_1_pane_1->SetSizer(sizer_3);
    grid_sizer_1->Add(iconSizeLabel, 0, wxALIGN_CENTER_VERTICAL, 0);
    grid_sizer_1->Add(iconSizeComboBox, 0, wxEXPAND, 0);
    grid_sizer_1->Add(orientationLabel, 0, wxALIGN_CENTER_VERTICAL, 0);
    grid_sizer_1->Add(orientationComboBox, 0, wxEXPAND, 0);
    grid_sizer_1->Add(skinLabel, 0, wxALIGN_CENTER_VERTICAL, 0);
    grid_sizer_1->Add(skinComboBox, 0, wxEXPAND, 0);
    grid_sizer_1->AddGrowableCol(1);
    sizer_4->Add(grid_sizer_1, 1, wxALL|wxEXPAND, 10);
    notebook_pane_2->SetSizer(sizer_4);
    notebook->AddPage(notebook_1_pane_1, wxT("General"));
    notebook->AddPage(notebook_pane_2, wxT("Appearance"));
    sizer_1->Add(notebook, 1, wxLEFT|wxRIGHT|wxTOP|wxEXPAND, 4);
    sizer_2->Add(saveButton, 0, wxRIGHT|wxALIGN_BOTTOM, 8);
    sizer_2->Add(cancelButton, 0, wxALIGN_BOTTOM, 0);
    sizer_1->Add(sizer_2, 0, wxALL|wxALIGN_RIGHT, 10);
    SetSizer(sizer_1);
    Layout();
    // end wxGlade
}

