// -*- C++ -*- generated by wxGlade 0.6.3

#include "ConfigDialogBase.h"

// begin wxGlade: ::extracode

// end wxGlade



ConfigDialogBase::ConfigDialogBase(wxWindow* parent, int id, const wxString& title, const wxPoint& pos, const wxSize& size, long style):
    wxDialog(parent, id, title, pos, size, wxDEFAULT_DIALOG_STYLE)
{
    // begin wxGlade: ConfigDialogBase::ConfigDialogBase
    notebook = new wxNotebook(this, ID_CDLG_MainNotebook, wxDefaultPosition, wxDefaultSize, 0);
    notebook_pane_5 = new wxPanel(notebook, wxID_ANY);
    notebook_pane_4 = new wxPanel(notebook, wxID_ANY);
    notebook_pane_3 = new wxPanel(notebook, wxID_ANY);
    notebook_pane_2 = new wxPanel(notebook, wxID_ANY);
    hotKeyGroupSizer_staticbox = new wxStaticBox(notebook_pane_3, -1, wxT("Hot key"));
    importExclusionSizer_staticbox = new wxStaticBox(notebook_pane_4, -1, wxT("#Exclude these files and folders from import operations:#"));
    availablePluginsBox_staticbox = new wxStaticBox(notebook_pane_5, -1, wxT("#Available plugins#"));
    notebook_1_pane_1 = new wxPanel(notebook, wxID_ANY);
    languageLabel = new wxStaticText(notebook_1_pane_1, wxID_ANY, wxT("Language:"));
    const wxString *languageComboBox_choices = NULL;
    languageComboBox = new wxComboBox(notebook_1_pane_1, wxID_ANY, wxT(""), wxDefaultPosition, wxDefaultSize, 0, languageComboBox_choices, wxCB_DROPDOWN|wxCB_READONLY);
    label_1 = new wxStaticText(notebook_1_pane_1, wxID_ANY, wxEmptyString);
    alwaysOnTopCheckBox = new wxCheckBox(notebook_1_pane_1, wxID_ANY, wxT("Always on top"));
    label_2 = new wxStaticText(notebook_1_pane_1, wxID_ANY, wxEmptyString);
    oneInstanceCheckBox = new wxCheckBox(notebook_1_pane_1, wxID_ANY, wxT("Allow only one instance of %s at a time"));
    label_5 = new wxStaticText(notebook_1_pane_1, wxID_ANY, wxEmptyString);
    installAutorunButton = new wxButton(notebook_1_pane_1, ID_CDLG_BUTTON_InstallAutorunButton, wxT("#Install autorun file#"));
    label_3 = new wxStaticText(notebook_1_pane_1, wxID_ANY, wxEmptyString);
    checkForUpdateButton = new wxButton(notebook_1_pane_1, ID_CDLG_BUTTON_CheckForUpdate, wxT("Check for update"));
    iconSizeLabel = new wxStaticText(notebook_pane_2, wxID_ANY, wxT("Icon size:"));
    const wxString *iconSizeComboBox_choices = NULL;
    iconSizeComboBox = new wxComboBox(notebook_pane_2, wxID_ANY, wxT(""), wxDefaultPosition, wxDefaultSize, 0, iconSizeComboBox_choices, wxCB_DROPDOWN|wxCB_READONLY);
    orientationLabel = new wxStaticText(notebook_pane_2, wxID_ANY, wxT("Orientation:"));
    const wxString *orientationComboBox_choices = NULL;
    orientationComboBox = new wxComboBox(notebook_pane_2, wxID_ANY, wxT(""), wxDefaultPosition, wxDefaultSize, 0, orientationComboBox_choices, wxCB_DROPDOWN|wxCB_READONLY);
    skinLabel = new wxStaticText(notebook_pane_2, wxID_ANY, wxT("Skin:"));
    const wxString *skinComboBox_choices = NULL;
    skinComboBox = new wxComboBox(notebook_pane_2, wxID_ANY, wxT(""), wxDefaultPosition, wxDefaultSize, 0, skinComboBox_choices, wxCB_DROPDOWN|wxCB_READONLY);
    autohideCheckBox = new wxCheckBox(notebook_pane_3, wxID_ANY, wxT("Hide after launching an application"));
    multiLaunchAutoRunCheckBox = new wxCheckBox(notebook_pane_3, wxID_ANY, wxT("#Run multi-launch group on startup#"));
    closeAppOnEjectCheckBox = new wxCheckBox(notebook_pane_3, wxID_ANY, wxT("#When ejecting the drive, close the apps that are locking it#"));
    hotKeyCtrlCheckBox = new wxCheckBox(notebook_pane_3, wxID_ANY, wxT("Ctrl +"));
    hotKeyAltCheckBox = new wxCheckBox(notebook_pane_3, wxID_ANY, wxT("Alt +"));
    hotKeyShiftCheckBox = new wxCheckBox(notebook_pane_3, wxID_ANY, wxT("Shift +"));
    const wxString *hotKeyComboBox_choices = NULL;
    hotKeyComboBox = new wxComboBox(notebook_pane_3, wxID_ANY, wxT(""), wxDefaultPosition, wxDefaultSize, 0, hotKeyComboBox_choices, wxCB_DROPDOWN|wxCB_READONLY);
    importExclusionTextBox = new wxTextCtrl(notebook_pane_4, wxID_ANY, wxEmptyString, wxDefaultPosition, wxDefaultSize, wxTE_MULTILINE|wxTE_WORDWRAP);
    pluginListView = new wxListCtrl(notebook_pane_5, ID_CDLG_BUTTON_PluginListView, wxDefaultPosition, wxDefaultSize, wxLC_REPORT|wxLC_SINGLE_SEL|wxSTATIC_BORDER);
    enablePluginButton = new wxButton(notebook_pane_5, ID_CDLG_BUTTON_EnablePlugin, wxT("#Enable#"));
    disablePluginButton = new wxButton(notebook_pane_5, ID_CDLG_BUTTON_DisablePlugin, wxT("#Disable#"));
    pluginChangeInfoLabel = new wxStaticText(notebook_pane_5, wxID_ANY, wxT("#Changes made to plugins will only be active the next time %s is started#"));
    saveButton = new wxButton(this, ID_CDLG_BUTTON_Save, wxT("Save"));
    cancelButton = new wxButton(this, wxID_CANCEL, wxT("Cancel"));

    set_properties();
    do_layout();
    // end wxGlade
}


void ConfigDialogBase::set_properties()
{
    // begin wxGlade: ConfigDialogBase::set_properties
    SetTitle(wxT("dialog_1"));
    SetSize(wxSize(459, 314));
    // end wxGlade
}


void ConfigDialogBase::do_layout()
{
    // begin wxGlade: ConfigDialogBase::do_layout
    wxBoxSizer* sizer_1 = new wxBoxSizer(wxVERTICAL);
    wxBoxSizer* sizer_2 = new wxBoxSizer(wxHORIZONTAL);
    wxBoxSizer* sizer_7 = new wxBoxSizer(wxHORIZONTAL);
    wxBoxSizer* sizer_8 = new wxBoxSizer(wxVERTICAL);
    wxBoxSizer* sizer_10 = new wxBoxSizer(wxHORIZONTAL);
    wxStaticBoxSizer* availablePluginsBox = new wxStaticBoxSizer(availablePluginsBox_staticbox, wxHORIZONTAL);
    wxBoxSizer* sizer_6 = new wxBoxSizer(wxHORIZONTAL);
    wxStaticBoxSizer* importExclusionSizer = new wxStaticBoxSizer(importExclusionSizer_staticbox, wxVERTICAL);
    wxBoxSizer* sizer_5 = new wxBoxSizer(wxHORIZONTAL);
    wxFlexGridSizer* grid_sizer_2 = new wxFlexGridSizer(3, 1, 8, 8);
    wxStaticBoxSizer* hotKeyGroupSizer = new wxStaticBoxSizer(hotKeyGroupSizer_staticbox, wxHORIZONTAL);
    wxFlexGridSizer* grid_sizer_3 = new wxFlexGridSizer(1, 4, 8, 8);
    wxBoxSizer* sizer_4 = new wxBoxSizer(wxHORIZONTAL);
    wxFlexGridSizer* grid_sizer_1 = new wxFlexGridSizer(3, 2, 8, 8);
    wxBoxSizer* sizer_3 = new wxBoxSizer(wxHORIZONTAL);
    wxFlexGridSizer* generalGridSizer = new wxFlexGridSizer(6, 2, 8, 8);
    generalGridSizer->Add(languageLabel, 0, wxALIGN_CENTER_VERTICAL, 0);
    generalGridSizer->Add(languageComboBox, 0, wxEXPAND, 0);
    generalGridSizer->Add(label_1, 0, 0, 0);
    generalGridSizer->Add(alwaysOnTopCheckBox, 0, 0, 0);
    generalGridSizer->Add(label_2, 0, 0, 0);
    generalGridSizer->Add(oneInstanceCheckBox, 0, 0, 0);
    generalGridSizer->Add(label_5, 0, 0, 0);
    generalGridSizer->Add(installAutorunButton, 0, wxEXPAND, 0);
    generalGridSizer->Add(label_3, 0, 0, 0);
    generalGridSizer->Add(checkForUpdateButton, 0, wxEXPAND, 0);
    generalGridSizer->AddGrowableCol(1);
    sizer_3->Add(generalGridSizer, 1, wxALL|wxEXPAND, 10);
    notebook_1_pane_1->SetSizer(sizer_3);
    grid_sizer_1->Add(iconSizeLabel, 0, wxALIGN_CENTER_VERTICAL, 0);
    grid_sizer_1->Add(iconSizeComboBox, 0, wxEXPAND, 0);
    grid_sizer_1->Add(orientationLabel, 0, wxALIGN_CENTER_VERTICAL, 0);
    grid_sizer_1->Add(orientationComboBox, 0, wxEXPAND, 0);
    grid_sizer_1->Add(skinLabel, 0, wxALIGN_CENTER_VERTICAL, 0);
    grid_sizer_1->Add(skinComboBox, 0, wxEXPAND, 0);
    grid_sizer_1->AddGrowableCol(1);
    sizer_4->Add(grid_sizer_1, 1, wxALL|wxEXPAND, 10);
    notebook_pane_2->SetSizer(sizer_4);
    grid_sizer_2->Add(autohideCheckBox, 0, wxEXPAND, 0);
    grid_sizer_2->Add(multiLaunchAutoRunCheckBox, 0, wxEXPAND, 0);
    grid_sizer_2->Add(closeAppOnEjectCheckBox, 0, 0, 0);
    grid_sizer_3->Add(hotKeyCtrlCheckBox, 0, 0, 0);
    grid_sizer_3->Add(hotKeyAltCheckBox, 0, 0, 0);
    grid_sizer_3->Add(hotKeyShiftCheckBox, 0, 0, 0);
    grid_sizer_3->Add(hotKeyComboBox, 0, 0, 0);
    hotKeyGroupSizer->Add(grid_sizer_3, 1, wxALL|wxEXPAND, 6);
    grid_sizer_2->Add(hotKeyGroupSizer, 1, wxEXPAND, 0);
    grid_sizer_2->AddGrowableCol(0);
    sizer_5->Add(grid_sizer_2, 1, wxALL|wxEXPAND, 10);
    notebook_pane_3->SetSizer(sizer_5);
    importExclusionSizer->Add(importExclusionTextBox, 1, wxALL|wxEXPAND, 8);
    sizer_6->Add(importExclusionSizer, 1, wxALL|wxEXPAND, 8);
    notebook_pane_4->SetSizer(sizer_6);
    availablePluginsBox->Add(pluginListView, 1, wxALL|wxEXPAND, 8);
    sizer_8->Add(availablePluginsBox, 1, wxEXPAND, 0);
    sizer_10->Add(enablePluginButton, 0, 0, 0);
    sizer_10->Add(disablePluginButton, 0, wxLEFT, 8);
    sizer_8->Add(sizer_10, 0, wxTOP|wxEXPAND, 8);
    sizer_8->Add(pluginChangeInfoLabel, 0, wxTOP, 8);
    sizer_7->Add(sizer_8, 1, wxALL|wxEXPAND, 8);
    notebook_pane_5->SetSizer(sizer_7);
    notebook->AddPage(notebook_1_pane_1, wxT("General"));
    notebook->AddPage(notebook_pane_2, wxT("Appearance"));
    notebook->AddPage(notebook_pane_3, wxT("Operations"));
    notebook->AddPage(notebook_pane_4, wxT("#Import#"));
    notebook->AddPage(notebook_pane_5, wxT("#Plugins#"));
    sizer_1->Add(notebook, 1, wxLEFT|wxRIGHT|wxTOP|wxEXPAND, 4);
    sizer_2->Add(saveButton, 0, wxRIGHT|wxALIGN_BOTTOM, 8);
    sizer_2->Add(cancelButton, 0, wxALIGN_BOTTOM, 0);
    sizer_1->Add(sizer_2, 0, wxALL|wxALIGN_RIGHT, 10);
    SetSizer(sizer_1);
    Layout();
    // end wxGlade
}

