// -*- C++ -*- generated by wxGlade 0.6.3

#include "ShortcutEditorDialogBase.h"

// begin wxGlade: ::extracode

// end wxGlade



ShortcutEditorDialogBase::ShortcutEditorDialogBase(wxWindow* parent, int id, const wxString& title, const wxPoint& pos, const wxSize& size, long style):
    wxDialog(parent, id, title, pos, size, wxDEFAULT_DIALOG_STYLE)
{
    // begin wxGlade: ShortcutEditorDialogBase::ShortcutEditorDialogBase
    nameLabel = new wxStaticText(this, wxID_ANY, wxT("Name:"));
    nameTextBox = new wxTextCtrl(this, wxID_ANY, wxEmptyString);
    locationLabel = new wxStaticText(this, wxID_ANY, wxT("Location:"));
    locationTextBox = new wxTextCtrl(this, wxID_ANY, wxEmptyString);
    browseButton = new wxButton(this, ID_SHORTCUTDLG_BUTTON_Browse, wxT("..."));
    parametersLabel = new wxStaticText(this, wxID_ANY, wxT("Parameters:"));
    parametersTextBox = new wxTextCtrl(this, wxID_ANY, wxEmptyString);
    iconLabel = new wxStaticText(this, wxID_ANY, wxT("Icon:"));
    iconStaticBitmap = new wxStaticBitmap(this, wxID_ANY, wxNullBitmap);
    changeIconButton = new wxButton(this, ID_SHORTCUTDLG_BUTTON_ChangeIcon, wxT("Change icon..."));
    useDefaultIconButton = new wxButton(this, ID_SHORTCUTDLG_BUTTON_UseDefaultIcon, wxT("#Use default#"));
    saveButton = new wxButton(this, ID_BUTTON_Save, wxT("Save"));
    cancelButton = new wxButton(this, wxID_CANCEL, wxT("Cancel"));

    set_properties();
    do_layout();
    // end wxGlade
}


void ShortcutEditorDialogBase::set_properties()
{
    // begin wxGlade: ShortcutEditorDialogBase::set_properties
    SetTitle(wxT("Edit shortcut"));
    SetSize(wxSize(403, 234));
    browseButton->SetMinSize(wxSize(25, -1));
    iconStaticBitmap->SetMinSize(wxSize(32, 32));
    // end wxGlade
}


void ShortcutEditorDialogBase::do_layout()
{
    // begin wxGlade: ShortcutEditorDialogBase::do_layout
    wxBoxSizer* mainSizer = new wxBoxSizer(wxVERTICAL);
    wxBoxSizer* saveCancelSizer = new wxBoxSizer(wxHORIZONTAL);
    wxFlexGridSizer* inputSizers = new wxFlexGridSizer(4, 2, 10, 8);
    wxFlexGridSizer* grid_sizer_1 = new wxFlexGridSizer(1, 3, 0, 8);
    wxBoxSizer* sizer_4 = new wxBoxSizer(wxHORIZONTAL);
    inputSizers->Add(nameLabel, 0, wxALIGN_CENTER_VERTICAL, 0);
    inputSizers->Add(nameTextBox, 0, wxEXPAND, 0);
    inputSizers->Add(locationLabel, 0, wxALIGN_CENTER_VERTICAL, 0);
    sizer_4->Add(locationTextBox, 1, wxRIGHT|wxALIGN_CENTER_VERTICAL, 8);
    sizer_4->Add(browseButton, 0, 0, 0);
    inputSizers->Add(sizer_4, 1, wxEXPAND, 0);
    inputSizers->Add(parametersLabel, 0, wxALIGN_CENTER_VERTICAL, 0);
    inputSizers->Add(parametersTextBox, 0, wxEXPAND, 0);
    inputSizers->Add(iconLabel, 0, wxALIGN_CENTER_VERTICAL, 0);
    grid_sizer_1->Add(iconStaticBitmap, 0, 0, 0);
    grid_sizer_1->Add(changeIconButton, 0, wxALIGN_CENTER_VERTICAL, 0);
    grid_sizer_1->Add(useDefaultIconButton, 0, wxALIGN_CENTER_VERTICAL, 0);
    inputSizers->Add(grid_sizer_1, 1, wxEXPAND, 0);
    inputSizers->AddGrowableCol(1);
    mainSizer->Add(inputSizers, 0, wxALL|wxEXPAND, 10);
    saveCancelSizer->Add(saveButton, 0, wxRIGHT|wxALIGN_BOTTOM, 8);
    saveCancelSizer->Add(cancelButton, 0, wxALIGN_BOTTOM, 0);
    mainSizer->Add(saveCancelSizer, 1, wxRIGHT|wxBOTTOM|wxALIGN_RIGHT, 10);
    SetSizer(mainSizer);
    Layout();
    // end wxGlade
}

