// -*- C++ -*- generated by wxGlade 0.6.3 on Sun Oct 19 22:20:23 2008

#include <wx/wx.h>
#include <wx/image.h>
// begin wxGlade: ::dependencies
// end wxGlade


#ifndef SHORTCUTEDITORFRAMEBASE_H
#define SHORTCUTEDITORFRAMEBASE_H


// begin wxGlade: ::extracode
// end wxGlade


class ShortcutEditorFrameBase: public wxFrame {
public:
    // begin wxGlade: ShortcutEditorFrameBase::ids
    // end wxGlade

    ShortcutEditorFrameBase(wxWindow* parent, int id, const wxString& title, const wxPoint& pos=wxDefaultPosition, const wxSize& size=wxDefaultSize, long style=wxDEFAULT_FRAME_STYLE);

private:
    // begin wxGlade: ShortcutEditorFrameBase::methods
    void set_properties();
    void do_layout();
    // end wxGlade

protected:
    // begin wxGlade: ShortcutEditorFrameBase::attributes
    wxStaticText* nameLabel;
    wxTextCtrl* nameTextBox;
    wxStaticText* locationLabel;
    wxTextCtrl* locationTextBox;
    wxButton* locationButton;
    wxButton* saveButton;
    wxButton* cancelButton;
    // end wxGlade
}; // wxGlade: end class


#endif // SHORTCUTEDITORFRAMEBASE_H
