// -*- C++ -*- generated by wxGlade 0.6.3

#include <wx/wx.h>
#include <wx/image.h>
// begin wxGlade: ::dependencies
// end wxGlade


#ifndef SHORTCUTEDITORDIALOGBASE_H
#define SHORTCUTEDITORDIALOGBASE_H


// begin wxGlade: ::extracode
enum {
  ID_BUTTON_Save,
  ID_BUTTON_Cancel,
  ID_BUTTON_SelectFile,
  ID_BUTTON_SelectFolder,
  ID_SHORTCUTDLG_BUTTON_ChangeIcon,
  ID_SHORTCUTDLG_BUTTON_UseDefaultIcon,
  ID_SHORTCUTDLG_BUTTON_Browse
};
// end wxGlade


class ShortcutEditorDialogBase: public wxDialog {
public:
    // begin wxGlade: ShortcutEditorDialogBase::ids
    // end wxGlade

    ShortcutEditorDialogBase(wxWindow* parent, int id, const wxString& title, const wxPoint& pos=wxDefaultPosition, const wxSize& size=wxDefaultSize, long style=wxDEFAULT_DIALOG_STYLE);

private:
    // begin wxGlade: ShortcutEditorDialogBase::methods
    void set_properties();
    void do_layout();
    // end wxGlade

protected:
    // begin wxGlade: ShortcutEditorDialogBase::attributes
    wxStaticText* nameLabel;
    wxTextCtrl* nameTextBox;
    wxStaticText* locationLabel;
    wxTextCtrl* locationTextBox;
    wxButton* browseButton;
    wxStaticText* label_1;
    wxStaticText* locationTextBoxDesc;
    wxStaticText* parametersLabel;
    wxTextCtrl* parametersTextBox;
    wxStaticText* iconLabel;
    wxStaticBitmap* iconStaticBitmap;
    wxButton* changeIconButton;
    wxButton* useDefaultIconButton;
    wxButton* saveButton;
    wxButton* cancelButton;
    // end wxGlade
}; // wxGlade: end class


#endif // SHORTCUTEDITORDIALOGBASE_H
